import {CheckModelRequestDtoSchema, type CheckModelRequestDto} from "nbook/shared/dto/app-settings.dto";
import {loadGlobalEffectiveConfigSync} from "nbook/server/config/config-service";
import {checkModelHealth, withSavedProviderApiKey} from "nbook/server/utils/model-settings";
import {validateBody} from "nbook/server/utils/novel-chapter";
import type {H3Event} from "h3";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Config"
    ],
    "summary": "Check health of a single model",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "provider": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string",
                                    "minLength": 1,
                                    "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]*$"
                                },
                                "name": {
                                    "type": "string",
                                    "minLength": 1
                                },
                                "api": {
                                    "default": null,
                                    "nullable": true,
                                    "type": "string",
                                    "minLength": 1
                                },
                                "options": {
                                    "type": "object",
                                    "properties": {
                                        "apiKey": {
                                            "default": "",
                                            "type": "string"
                                        },
                                        "baseURL": {
                                            "default": "",
                                            "type": "string"
                                        },
                                        "proxy": {
                                            "default": "",
                                            "type": "string"
                                        },
                                        "timeoutMs": {
                                            "default": null,
                                            "nullable": true,
                                            "type": "integer",
                                            "exclusiveMinimum": true,
                                            "maximum": 9007199254740991
                                        },
                                        "requestOptions": {
                                            "default": {},
                                            "type": "object",
                                            "additionalProperties": {
                                                "$ref": "#/definitions/__schema0"
                                            }
                                        }
                                    },
                                    "required": [
                                        "apiKey",
                                        "baseURL",
                                        "proxy",
                                        "timeoutMs",
                                        "requestOptions"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "required": [
                                "id",
                                "name",
                                "api",
                                "options"
                            ],
                            "additionalProperties": false
                        },
                        "model": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string",
                                    "minLength": 1
                                },
                                "id": {
                                    "type": "string",
                                    "minLength": 1
                                },
                                "group": {},
                                "provider": {},
                                "api": {
                                    "default": null,
                                    "nullable": true,
                                    "type": "string",
                                    "minLength": 1
                                },
                                "baseUrl": {},
                                "reasoning": {
                                    "default": null,
                                    "nullable": true,
                                    "type": "boolean"
                                },
                                "input": {
                                    "default": null,
                                    "nullable": true,
                                    "minItems": 1,
                                    "type": "array",
                                    "items": {
                                        "type": "string",
                                        "enum": [
                                            "text",
                                            "image"
                                        ]
                                    }
                                },
                                "maxTokens": {
                                    "default": null,
                                    "nullable": true,
                                    "type": "integer",
                                    "exclusiveMinimum": true,
                                    "maximum": 9007199254740991
                                },
                                "cost": {
                                    "default": null,
                                    "nullable": true,
                                    "type": "object",
                                    "properties": {
                                        "input": {
                                            "default": 0,
                                            "type": "number"
                                        },
                                        "output": {
                                            "default": 0,
                                            "type": "number"
                                        },
                                        "cacheRead": {
                                            "default": 0,
                                            "type": "number"
                                        },
                                        "cacheWrite": {
                                            "default": 0,
                                            "type": "number"
                                        }
                                    },
                                    "required": [
                                        "input",
                                        "output",
                                        "cacheRead",
                                        "cacheWrite"
                                    ],
                                    "additionalProperties": false
                                },
                                "compat": {
                                    "default": null,
                                    "nullable": true,
                                    "type": "object",
                                    "additionalProperties": {
                                        "$ref": "#/definitions/__schema1"
                                    }
                                },
                                "contextWindowTokens": {
                                    "default": null,
                                    "nullable": true,
                                    "type": "integer",
                                    "exclusiveMinimum": true,
                                    "maximum": 9007199254740991
                                }
                            },
                            "required": [
                                "name",
                                "id",
                                "group",
                                "provider",
                                "api",
                                "baseUrl",
                                "reasoning",
                                "input",
                                "maxTokens",
                                "cost",
                                "compat",
                                "contextWindowTokens"
                            ],
                            "additionalProperties": false
                        },
                        "useSavedApiKey": {
                            "default": true,
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "provider",
                        "model",
                        "useSavedApiKey"
                    ],
                    "additionalProperties": false,
                    "definitions": {
                        "__schema0": {
                            "anyOf": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "number"
                                },
                                {
                                    "type": "boolean"
                                },
                                {
                                    "type": "string",
                                    "nullable": true,
                                    "enum": [
                                        null
                                    ]
                                },
                                {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/__schema0"
                                    }
                                },
                                {
                                    "type": "object",
                                    "additionalProperties": {
                                        "$ref": "#/definitions/__schema0"
                                    }
                                }
                            ]
                        },
                        "__schema1": {
                            "anyOf": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "number"
                                },
                                {
                                    "type": "boolean"
                                },
                                {
                                    "type": "string",
                                    "nullable": true,
                                    "enum": [
                                        null
                                    ]
                                },
                                {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/__schema1"
                                    }
                                },
                                {
                                    "type": "object",
                                    "additionalProperties": {
                                        "$ref": "#/definitions/__schema1"
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "success": {
                                "type": "boolean"
                            },
                            "latencyMs": {
                                "nullable": true,
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 9007199254740991
                            },
                            "message": {
                                "type": "string",
                                "minLength": 1
                            }
                        },
                        "required": [
                            "success",
                            "latencyMs",
                            "message"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

/**
 * 将 HTTP 请求/响应断开转换为模型检查可用的 AbortSignal。
 */
function createModelCheckAbortSignal(event: H3Event): {signal: AbortSignal; cleanup: () => void} {
    const controller = new AbortController();
    const abort = () => {
        if (!controller.signal.aborted) {
            controller.abort();
        }
    };
    const abortOnRequestClose = () => {
        if (event.node.req.aborted) {
            abort();
        }
    };
    const abortOnResponseClose = () => {
        if (!event.node.res.writableEnded) {
            abort();
        }
    };

    if (event.node.req.aborted || event.node.res.destroyed) {
        abort();
    }
    event.node.req.on("aborted", abort);
    event.node.req.on("close", abortOnRequestClose);
    event.node.res.on("close", abortOnResponseClose);

    return {
        signal: controller.signal,
        cleanup: () => {
            event.node.req.off("aborted", abort);
            event.node.req.off("close", abortOnRequestClose);
            event.node.res.off("close", abortOnResponseClose);
        },
    };
}

/**
 * 单模型健康检查。草稿未携带明文 API Key 时，回退读取已保存的 Global Config secret。
 */
export default defineEventHandler(async (event) => {
    const body = await validateBody<CheckModelRequestDto>(event, CheckModelRequestDtoSchema);
    const requestAbort = createModelCheckAbortSignal(event);
    const savedApiKey = loadGlobalEffectiveConfigSync().models.providers[body.provider.id]?.options.apiKey;
    const provider = body.useSavedApiKey
        ? withSavedProviderApiKey(body.provider, savedApiKey)
        : body.provider;
    try {
        return await checkModelHealth(provider, body.model, {signal: requestAbort.signal});
    } finally {
        requestAbort.cleanup();
    }
});
