/* eslint-disable */
// This file is generated by scripts/prepare-system-profile-metadata.ts.
// It is a stable IDE entry for ProfileVariableAccessor authoring types.
// Runtime variable truth stays in registry and compiled artifacts.

import type {JsonValue} from "nbook/server/agent/messages/types";
declare module "nbook/server/agent/variables/types" {
    interface ProfileVariableValueMap {
        "client.currentProjectWorkspace": string | null;
        "client.ide": Record<string, JsonValue>;
        "client.ide.activePanel": string | null;
        "client.ide.extra": string;
        "client.ide.panel": string | null;
        "client.ide.theme": string;
        "client.studio": Record<string, JsonValue>;
        "client.studio.currentChapterLabel": string | null;
        "client.studio.didSwitchFile": boolean;
        "client.studio.extra": string;
        "client.studio.novelId": string;
        "client.studio.previousChapterLabel": string | null;
        "client.studio.previousChapterTitle": string | null;
        "client.studio.previousSelectedFilePath": string | null;
        "client.studio.selectedFilePath": string | null;
        "client.studio.selectedStorySceneId": string | null;
        "client.studio.selectedStoryThreadId": string | null;
        "client.studio.selectionVersion": number;
        "client.studio.workspace": string | null;
        "client.studio.workspaceKind": "novel" | "user-assets";
    }
}
import type {JsonValue} from "nbook/server/agent/messages/types";
declare module "nbook/server/agent/variables/types" {
    interface ProfileVariableValueMap {
    }
}
import type {JsonValue} from "nbook/server/agent/messages/types";
declare module "nbook/server/agent/variables/types" {
    interface ProfileVariableValueMap {
    }
}
import type {JsonValue} from "nbook/server/agent/messages/types";
declare module "nbook/server/agent/variables/types" {
    interface ProfileVariableValueMap {
    }
}
import type {JsonValue} from "nbook/server/agent/messages/types";
declare module "nbook/server/agent/variables/types" {
    interface ProfileVariableValueMap {
    }
}
import type {JsonValue} from "nbook/server/agent/messages/types";
declare module "nbook/server/agent/variables/types" {
    interface ProfileVariableValueMap {
    }
}
