/**
 * 内置中文组名到稳定英文 namespace 的映射。
 */
export const DEFAULT_NAMESPACE_ALIASES: Record<string, string> = {
    "填充短语": "filler",
    "机械过渡": "transition.mechanical",
    "二元对比": "contrast.binary",
    "负向列举": "contrast.negative-listing",
    "喉舌式开头": "opening.mouthpiece",
    "元叙述": "meta",
    "公式化设问": "rhetorical-question",
    "强调拐杖": "emphasis-crutch",
    "商务黑话": "jargon.business",
    "懒惰绝对词": "absolute",
    "抽象空洞": "abstraction.hollow",
    "行动者": "actor.hidden",
    "节奏与评分": "rhythm",
    "形副词系": "modifier",
    "形副词[可选]": "modifier",
    "形副量词": "modifier.measure",
    "删陈词滥调": "cliche",
    "修剪复合句": "sentence.compound",
    "修剪比喻类": "metaphor",
    "人体词汇": "vocabulary.body",
    "人体词汇转换": "vocabulary.body",
    "R18词汇": "vocabulary.r18",
    "学术与解剖词汇": "vocabulary.academic-anatomy",
    "动作与神态": "action-expression",
    "颜色描写": "color-description",
    "破折号": "punctuation.dash",
    "连续符号去重": "punctuation.dedup",
    "正则-高级替换": "regex.advanced",
    "正则-杀“一声”": "sound.once",
    "八股句式/短语删除": "cliche.baguwen",
    "词汇替换[可选]": "vocabulary.optional",
    "处理多类型增殖": "proliferation.mixed",
    "处理多种增殖[选开]": "proliferation.mixed",
    "处理破折号增殖（和角色卡交互有冲突关掉这个开新对话）": "punctuation.dash-proliferation",
    "处理破折号增殖（角色卡交互有问题关掉这个）": "punctuation.dash-proliferation",
    "处理—…增殖[选开]": "punctuation.dash-ellipsis-proliferation",
    "合并较短段落[选开]": "paragraph.merge-short",
    "分割较长段落[选开]": "paragraph.split-long",
    "不是而是": "contrast.binary",
    "三": "numeral.three",
    "合集 3": "collection.deepseek",
    "语气": "tone",
    "像像像": "metaphor.like",
    "嘴角与生理泪水": "cliche.body-reaction",
    "极其替换": "modifier.extreme",
    "极其删除": "modifier.extreme",
    "由于删除": "causal.due-to",
    "生理删除": "modifier.physiological",
};
